### PR TITLE
Korean Update - NyaamZ

### PR DESCRIPTION
**Pull request by NyaamZ**
Korean Update - NyaamZ

### CODE REVIEW

**Comment by OrionFive** [comment]
Thanks!

**Comment by OrionFive** [comment]
Good job! Did you use a tool to create the structure or did you do it all by hand?

**Comment by NyaamZ** [comment]
I used a tool (RimTrans). previous korean version was missing a lot.

**Comment by OrionFive** [comment]
Cool!
Could you do me a favor and generate the English language files for me?

**Pull request merged**
